### ISSUE TITLE
implement a red-black tree

### ISSUE THREAD

**Issue by karnaksp** [karnaksp/-containers-#1]
implement a red-black tree to implement a set and map

![Image](https://github.com/karnaksp/-containers-/assets/109888488/ea540ad4-d5ac-4468-9b58-06acd8fbbf39)

**Comment by karnaksp** [comment]
**Взял в работу, босс**

**Comment by karnaksp** [comment]
добавил итератор по черно-красному дереву, однако на самой итерируемости есть проблемы. не проходит простые тесты. для ci я их закомментил
![image](https://github.com/karnaksp/-containers-/assets/109888488/9c95da92-97bc-48c4-9111-de616538d081)

**Comment by Hultyrhik** [comment]
Комменты вижу
