### ISSUE TITLE
List

### ISSUE THREAD

**Issue by karnaksp** [karnaksp/-containers-#3]
# List Member type

| Member type      | Definition                                                   |
|------------------|--------------------------------------------------------------|
| value_type       | T defines the type of an element (T is a template parameter) |
| reference        | T & defines the type of the reference to an element          |
| const_reference  | const T & defines the type of the constant reference         |
| iterator         | internal class ListIterator<T> defines the type for iterating through the container |
| const_iterator   | internal class ListConstIterator<T> defines the constant type for iterating through the container |
| size_type        | size_t defines the type of the container size (standard type is size_t) |

# List Functions

| Functions                               | Definition                                                                  |
|-----------------------------------------|-----------------------------------------------------------------------------|
| list()                                  | default constructor, creates an empty list                                 |
| list(size_type n)                      | parameterized constructor, creates the list of size n                       |
| list(std::initializer_list<value_type> const &items) | initializer list constructor, creates a list initizialized using std::initializer_list |
| list(const list &l)                   | copy constructor                                                            |
| list(list &&l)                        | move constructor                                                            |
| ~list()                                | destructor                                                                  |
| operator=(list &&l)                   | assignment operator overload for moving an object                           |

# List Element access

| Element access      | Definition                              |
|---------------------|-----------------------------------------|
| const_reference front() | access the first element                |
| const_reference back()  | access the last element                 |

# List Iterators

| Iterators          | Definition                               |
|--------------------|------------------------------------------|
| iterator begin()   | returns an iterator to the beginning     |
| iterator end()     | returns an iterator to the end           |

# List Capacity

| Capacity           | Definition                                  |
|--------------------|---------------------------------------------|
| bool empty()       | checks whether the container is empty       |
| size_type size()   | returns the number of elements              |
| size_type max_size() | returns the maximum possible number of elements |

# List Modifiers

| Modifiers                                | Definition                                                               |
|------------------------------------------|--------------------------------------------------------------------------|
| void clear()                             | clears the contents                                                      |
| iterator insert(iterator pos, const_reference value) | inserts element into concrete pos and returns the iterator that points to the new element |
| void erase(iterator pos)                | erases an element at pos                                                 |
| void push_back(const_reference value)   | adds an element to the end                                               |
| void pop_back()                          | removes the last element                                                 |
| void push_front(const_reference value)  | adds an element to the head                                              |
| void pop_front()                         | removes the first element                                                |
| void swap(list& other)                  | swaps the contents                                                       |
| void merge(list& other)                 | merges two sorted lists                                                   |
| void splice(const_iterator pos, list& other) | transfers elements from list other starting from pos                     |
| void reverse()                          | reverses the order of the elements                                        |
| void unique()                           | removes consecutive duplicate elements                                    |
| void sort()                             | sorts the elements                                                        |

**Comment by Hultyrhik** [comment]
Выбрал себя в качестве исполнителя
